language: node_js
node_js:
  - 0.6

before_script:
  - "curl -o test/sinon.js 'http://sinonjs.org/releases/sinon-1.5.2.js'"
  - "curl -o test/sinon-qunit.js 'http://sinonjs.org/releases/sinon-qunit-1.0.0.js'"
  - "curl -o resources/js-test-driver/JsTestDriver-1.3.3d.jar 'http://code.google.com/p/js-test-driver/downloads/detail?name=JsTestDriver-1.3.3d.jar&can=1&q='"
  - "curl -o resources/js-test-driver/coverage-1.3.5.serve-patch.jar 'http://js-test-driver.googlecode.com/issues/attachment?aid=3090011000&name=coverage-1.3.5.serve-patch.jar&token=NywXSnlAJ0XxMngWnWh8aram1Zk%3A1356934060231'"
  - "curl -o resources/js-test-driver/equiv.js 'https://raw.github.com/exnor/QUnit-to-JsTestDriver-adapter/master/equiv.js'"
  - "java -jar resources/js-test-driver/JsTestDriver-1.3.3d.jar --basePath ./resources/js-test-driver --config resources/js-test-driver/jsTestDriver.conf --port 9876 &"
  - "sleep 3"
  - "phantomjs resources/js-test-driver-phantomjs/phantomjs-jstd.js &"
  - "sleep 3"