language: node_js
node_js:
  - 0.6

before_script:
  - "curl -o test/sinon.js 'http://sinonjs.org/releases/sinon-1.5.2.js'"
  - "curl -o test/sinon-qunit.js 'http://sinonjs.org/releases/sinon-qunit-1.0.0.js'"
  - "curl -o resources/js-test-driver/JsTestDriver-1.3.3d.jar 'http://js-test-driver.googlecode.com/files/JsTestDriver-1.3.3d.jar'"
  - "curl -o resources/js-test-driver/equiv.js 'https://raw.github.com/exnor/QUnit-to-JsTestDriver-adapter/master/equiv.js'"
  - "java -jar resources/js-test-driver/JsTestDriver-1.3.3d.jar --basePath ./resources/js-test-driver --config resources/js-test-driver/jsTestDriver.conf --port 9876 &"
  - "sleep 3"
  - "phantomjs resources/js-test-driver-phantomjs/phantomjs-jstd.js &"
  - "sleep 3"