language: node_js
node_js:
  - 0.6

before_script:
  - "java -jar resources/js-test-driver/JsTestDriver-1.3.3d.jar --basePath ./resources/js-test-driver --config resources/js-test-driver/jsTestDriver.conf --port 9876 &"
  - "sleep 3"
  - "phantomjs test/phantomjs-jstd.js &"
  - "sleep 3"