language: node_js
node_js:
  - 0.6

jdk:
  - oraclejdk7

before_install:
  - "sudo add-apt-repository ppa:webupd8team/java"
  - "sudo apt-get update"
  - "sudo apt-get install oracle-java7-installer"

before_script:
  - "cake -u jstd"

after_script:
  - "cake -d jstd"
