language: node_js
node_js:
  - 0.6

before_script:
  - "ls test/qunit"
  - "ls test/qunit/qunit"
  - "java -jar resources/js-test-driver/JsTestDriver-1.3.3d.jar --config resources/js-test-driver/jsTestDriver.conf --port 9876"
